# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SportFit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportFit
 pod 'Alamofire'
 pod 'IQKeyboardManagerSwift'
 pod 'SwiftyJSON'

  target 'SportFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportFitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
